// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDwEspnNThXx1LV-Z-hNLe47B-k8V_-8U',
    appId: '1:817332476039:web:fad44a08e71d97d2d34022',
    messagingSenderId: '817332476039',
    projectId: 'talleruniversidades',
    authDomain: 'talleruniversidades.firebaseapp.com',
    storageBucket: 'talleruniversidades.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI2385SDi3PYvFoKwvP8JZhFZo9RiEcy0',
    appId: '1:817332476039:android:d984867ae9b01fdad34022',
    messagingSenderId: '817332476039',
    projectId: 'talleruniversidades',
    storageBucket: 'talleruniversidades.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6siiMx4f-9fHTHjJNfA0bZ7nnY0Q0Q78',
    appId: '1:817332476039:ios:ac44934afcff7063d34022',
    messagingSenderId: '817332476039',
    projectId: 'talleruniversidades',
    storageBucket: 'talleruniversidades.firebasestorage.app',
    iosBundleId: 'com.example.parqueadero2025G2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6siiMx4f-9fHTHjJNfA0bZ7nnY0Q0Q78',
    appId: '1:817332476039:ios:ac44934afcff7063d34022',
    messagingSenderId: '817332476039',
    projectId: 'talleruniversidades',
    storageBucket: 'talleruniversidades.firebasestorage.app',
    iosBundleId: 'com.example.parqueadero2025G2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDwEspnNThXx1LV-Z-hNLe47B-k8V_-8U',
    appId: '1:817332476039:web:93714a580ecfb018d34022',
    messagingSenderId: '817332476039',
    projectId: 'talleruniversidades',
    authDomain: 'talleruniversidades.firebaseapp.com',
    storageBucket: 'talleruniversidades.firebasestorage.app',
  );

}